<?php
// Auto-generated photo index
// Generated by FTP Photo Manager

// Získej base URL
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https://' : 'http://';
$host = $_SERVER['HTTP_HOST'];
$scriptPath = dirname($_SERVER['SCRIPT_NAME']);
$scriptPath = rtrim($scriptPath, '/') . '/';
$baseUrl = $protocol . $host . $scriptPath;

$photos = [
    [
        'thumbnail' => 'thumbnail/example1.jpg',
        'thumbnail_url' => $baseUrl . 'thumbnail/example1.jpg',
        'original' => 'original/example1.jpg',
        'original_url' => $baseUrl . 'original/example1.jpg',
        'compress' => 'compress/example1.jpg',
        'compress_url' => $baseUrl . 'compress/example1.jpg',
        'filename' => 'example1.jpg'
    ],
    [
        'thumbnail' => 'thumbnail/example2.jpg',
        'thumbnail_url' => $baseUrl . 'thumbnail/example2.jpg',
        'original' => 'original/example2.jpg',
        'original_url' => $baseUrl . 'original/example2.jpg',
        'compress' => 'compress/example2.jpg',
        'compress_url' => $baseUrl . 'compress/example2.jpg',
        'filename' => 'example2.jpg'
    ],
];

$result = [
    'success' => true,
    'count' => count($photos),
    'base_url' => $baseUrl,
    'photos' => $photos
];

// Return JSON
header('Content-Type: application/json');
echo json_encode($result, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
?>
